# Mapping & règles d'affichage SMBG Carte
right_panel:
  # colonnes à afficher dans le volet droit (ordre Excel), plage G..AF
  range_excel: "G:AF"
  google_maps_column_letter: "H"   # transformée en bouton "Cliquer ici"
  hide_values: ["/", "-", ""]      # ne pas afficher ces valeurs
technical_columns:
  latitude: "AG"
  longitude: "AH"
  geocode_status: "AI"
  geocode_date: "AJ"
  reference: "AK"
  photos: "AL"
  active: "AM"
filters:
  # les filtres Région/Département se basent uniquement sur les valeurs présentes dans l'Excel
  region_column_names: ["Région", "Region"]
  department_column_names: ["Département", "Departement", "N° Département", "No Département", "Dept"]
modes:
  # colonnes loyers (masquées en mode client et remplacées par "Demander le loyer")
  rent_columns_letters: ["N", "O", "P"]
  default_mode: "client"   # "client" ou "interne" (surchargé par ?mode= dans l'URL)
branding:
  google_maps_button_label: "Cliquer ici"
  show_reference_banner: true
