SUPABASE_URL = "https://tonprojet.supabase.co"
SUPABASE_KEY = "eyJhbGciOi..."          # ta anon key Supabase
EXCEL_URL = "https://raw.githubusercontent.com/guillaume-smbg/smbg-carte/main/data/Excel_template_SMBG.xlsx"
R2_BASE_URL = "https://<accountid>.r2.cloudflarestorage.com/smbg-photos/"
